### ISSUE TITLE
Proof of Concept

### ISSUE THREAD

**Issue by lachlansneff** [nebulet/nebulet#5]
The ultimate goal for the next few months is to have a "working" proof-of-concept that demonstrates that executing WebAssembly in ring 0 is reasonably performant and safe. Development is moving much more quickly than I initially thought it would, but there's still quite a ways to go.

Here's what needs to happen:

- [x] Design a process and threading model.
- [x] Implement signature checking on external calls.
- [x] Design an abi interface between SIPs and the kernel.
- [ ] Benchmark and fuzz it!

I'll create issues for each of these when they come up.

**Comment by lachlansneff** [comment]
Just implemented signature checking. Much easier than I thought it would be!

**Comment by lachlansneff** [comment]
I'm thinking along the lines of having modules be packaged with manifests that describe what privileged they need, etc

```toml
[module]
name = "test-module"
version = "0.1.0"
privileges = [
    "fs/open",
    "io/stdout",
]
```
